# Generated by Django 5.0.6 on 2024-06-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_rename_author_tag_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["is_done", "-at_created"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
